version: '3.8'

services:
  app:
    image: my-springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./target:/app/target
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
